# Generated by Django 5.1.6 on 2025-05-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organization_api_key_organization_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='api_key',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='secret_key',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
