# Generated by Django 5.1.6 on 2025-05-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_organization_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='ssh_key',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
