# Generated by Django 5.1.6 on 2025-05-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_organization_ssh_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
