# Generated by Django 5.1.6 on 2025-02-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='updated_at',
        ),
    ]
