# Generated by Django 5.1.6 on 2025-02-19 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),

    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='organization_id',
        ),

    ]
