# Generated by Django 5.1.6 on 2025-02-24 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_contact_profile_contact'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='token',
            name='type',
            field=models.CharField(blank=True, choices=[('email_verification', 'Email Verification'), ('subscription_token', 'Subscription Token'), ('forgot_password', 'Password Forgotten')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
