# Generated by Django 5.1.6 on 2025-03-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='media',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='token',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
