# Generated by Django 5.1.6 on 2025-08-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, default='+1', max_length=10, null=True),
        ),
    ]
